version: '3.9'
services:
  b2s_angular_app:
    container_name: b2s-angular_app
    image: as-b2s-angular_app:1.0.0
    build: ./beatportToSpotifyFront
    ports:
      - 80:81
    depends_on:
      - b2s_java_app
  b2s_java_app:
    container_name: b2s-java_app
    image: as-b2s-java_app:1.0.0
    build: ./beatportToSpotify
    ports:
      - 8080:8081

